# Generated by Django 3.0.8 on 2021-05-26 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='The identifier field of the menu')),
                ('name', models.TextField(verbose_name='The name of the menu that is going to be served.')),
                ('date', models.DateField(verbose_name='The date which the menu is going to be served.')),
                ('expiration_date_time', models.DateTimeField(verbose_name='The limited date and time to request an option of a menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='The name of an option')),
                ('description', models.TextField(verbose_name='The description of a menu. It can contains ingredients or other required specification in order to let know  the employees the things used to prepare an option.')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
        ),
    ]
