# Generated by Django 3.0.8 on 2021-05-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210526_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
