# Generated by Django 3.0.8 on 2021-05-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.TextField(verbose_name='The username in slack of the employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slack_user',
            field=models.TextField(verbose_name='The slack user identifier in slack of the employee'),
        ),
    ]
